#! /bin/bash
USERS='user_del'
tmp=/tmp/input.$$

    mysql -B --column-names=0 -h192.168.1.13 -Dskrypt -uskrypt -p**** -e "SELECT r_pesel, r_data FROM rozliczenia WHERE r_status LIKE 'no'" | grep -v r_pesel,r_data >$tmp
    dopisz=`cat $tmp`
    echo "$dopisz">>user_del
    mysql -B -h192.168.1.13 -Dskrypt -uskrypt -p**** -e "UPDATE rozliczenia SET r_status='ok' WHERE r_status LIKE 'no'"

exec 0< $USERS
#tworzy ciag daty
AKTUALNA=`date +"%Y-%m-%d"`
while
    IFS='	' read PESEL DATA
do
    #sprawdza czy data sie zgadza
    if [[ $AKTUALNA = $DATA ]]
then
	#blokowanie w CRM2
	mysql -B -h192.168.1.3 -Dhr -uskrypt -p**** -e "UPDATE pracownicy_ewidencja SET czy_pracuje=0, status=0 WHERE pesel LIKE '%$PESEL%'"
	#blokowanie w CRM1
#	mysql -B -h192.168.1.3 -Dcapital -uskrypt -p**** -e "UPDATE cash_users SET czy_aktywne='n' WHERE pesel LIKE '%$PESEL%'"

	#Wyciaga z bazy login
#	mysql -B -h192.168.1.3 -Dcentrum -uskrypt -p**** -e "SELECT login FROM uzytkownicy_ewidencja WHERE pesel LIKE '%$PESEL%'"| grep -v login >$tmp

	#Skleja login
#	LOGIN1=`cat $tmp| cut -c -1`
#	LOGIN2=`cat $tmp| cut -c 3-`
#	LOGIN=`echo $LOGIN1$LOGIN2`

	#Laczy sie z 1.4 i wylacza konto w sambie
#	ssh -n root@192.168.1.4 "samba-tool user enable $LOGIN" 2>/dev/null

	#Zapisuje logi
#	echo "Zablokowano $LOGIN dnia `date | cut -c 6-`">>log 

fi
done
